spring:
  application:
    name: game-service
  datasource:
    url: ${GAME_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

lol:
  maxBans: ${LOL_SERVICE_MAX_BANS}
  championPoolSize: ${LOL_SERVICE_CHAMP_POOL_SIZE}
  eloGain: ${LOL_SERVICE_ELO_GAIN}
  eloDifficultyFactor: ${LOL_SERVICE_ELO_DIFFICULTY_FACTOR}
  eloPerformanceFactor: ${LOL_SERVICE_ELO_PERFORMANCE_FACTOR}
  maxEloGain: ${LOL_SERVICE_MAX_ELO_GAIN}
  eloDifficultyKFactor: ${LOL_SERVICE_ELO_DIFFICULTY_FACTOR}
  startingElo: ${LOL_SERVICE_ELO_GAIN}

server:
  port: 8082
