spring:
  application:
    name: security-service
  datasource:
    url: ${SECURITY_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

microservices:
  music:
    url: ${MUSIC_SERVICE_URL}
  game:
    url: ${GAME_SERVICE_URL}

server:
  port: 8080

